---

# Default compose file for production.

version: "3.6"
services:
  web:
    image: "jundice-app:prod"
    build:
      context: .
      dockerfile: docker/aio_app/Dockerfile
      args:
        BUILD_ENV: production
    depends_on:
      - redis
    environment:
      NEWS_REDIS_HOST: redis
    networks:
      - webnet
      - proxynet

  redis:
    image: "redis:6.0.6-alpine"
    networks:
      - webnet

  nginx:
    image: "nginx:1.19.1-alpine"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # configuration
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - proxynet

networks:
  # Network for your proxy server and application to connect them,
  # do not use it for anything else!
  proxynet:
  # Network for your internals, use it by default:
  webnet:
