---

# Default compose file for development.

version: "3.6"
services:
  web:
    image: "jundice-app:dev"
    build:
      context: .
      dockerfile: docker/aio_app/Dockerfile
      args:
        BUILD_ENV: development
    depends_on:
      - redis
    environment:
      NEWS_REDIS_HOST: redis
    networks:
      - webnet
      - proxynet
    volumes:
      # We only mount source code in development:
      - .:/code
    ports:
      # We only bind ports directly in development:
      - "8080:8080"

  redis:
    image: "redis:6.0.6-alpine"
    networks:
      - webnet
    ports:
      - "6379:6379"

  nginx:
    image: "nginx:1.19.1-alpine"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # configuration
    ports:
      - "8888:80"
    depends_on:
      - web
    networks:
      - proxynet


networks:
  # Network for your proxy server and application to connect them,
  # do not use it for anything else!
  proxynet:
  # Network for your internals, use it by default:
  webnet:
